export const FLIGHT_LIST_REQUEST = "FLIGHT_LIST_REQUEST";
export const FLIGHT_LIST_SUCCESS = "FLIGHT_LIST_SUCCESS";
export const FLIGHT_LIST_FAILED = "FLIGHT_LIST_FAILED";

export const FILTER_FLIGHT_LIST = "FILTER_FLIGHT_LIST";
